import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// PROJECT-SPECIFIC: Set this for each project
const PLUGIN_NAME = 'bible-portal';

// STANDARD: Dev vault path (same for all projects)
const DEV_VAULT_PATH = `/home/stephen/Documents/dev/vaults/dev-vault/.obsidian/plugins/${PLUGIN_NAME}`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,

	// NEW: Conditional output based on mode
	outfile: prod ? 'main.js' : `${DEV_VAULT_PATH}/main.js`,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
